### ISSUE TITLE
readme request

### ISSUE THREAD

**Issue by gsngsn123** [proro485/zrx-arbitrage-bot#1]
it is very helpful if u add commands for deploy and  execute the bot

**Comment by proro485** [comment]
i will add the steps required to readme. but just to let you know that it isn't profitable yet.

**Comment by gsngsn123** [comment]
no problem try both and will update u if any errors and bugs

**Comment by gsngsn123** [comment]
pls add  the steps

**Comment by proro485** [comment]
added the steps. if  you want anymore info, you can open another issue.
