### ISSUE TITLE
deployed

### ISSUE THREAD

**Issue by gsngsn123** [proro485/zrx-arbitrage-bot#2]
hi deployed but i when run the some html window opening and got error cont reach this see below image 
![Uploading 2022-02-27.png…]()

**Comment by proro485** [comment]
I cannot see the image you have uploaded.

**Comment by gsngsn123** [comment]
![2022-02-27](https://user-images.githubusercontent.com/33231545/155872453-f5f82cbc-58df-4d27-a58b-606542cd7d4e.png)

**Comment by proro485** [comment]
I have fixed the commands, you can check it now. Basically I was using the shorthand package provided by hardhat which allows me to just type "hh" instead of npx hardhat.

**Comment by gsngsn123** [comment]
ok
