### ISSUE TITLE
getbps edit

### ISSUE THREAD

**Issue by gsngsn123** [proro485/zrx-arbitrage-bot#4]
can pls explain how to edit this 

const getBPS = (amount = 30000) => {
    switch (amount) {
        case 30000:
            return 1;
        case 100:
            return 500;
        case 1000:
            return 50;
        case 2000:
            return 25;
        case 5000:
            return 8;
        case 10000:
            return 5;
        default:

**Comment by proro485** [comment]
just change the (amount = whatever value you want). if that amount is not in the case below just add the case and return the value of bps you want.
