### ISSUE TITLE
.env File

### ISSUE THREAD

**Issue by rinconcsc** [proro485/zrx-arbitrage-bot#5]
Hi 

I have two questions.
1. How can I modify the script so that the bot makes a certain swap in two certain exchanges of certain tokens when I run the program.
2. Where (in the directory) and how do I have to create the **.env** file

I am sorry if these are dumb questions, but _**I need your help :)**_

**Comment by proro485** [comment]
That can be done, but you have to do a lot of changes. I have a private repo for that and it has made me around 20$. But I would say it isn't worth it to find arbitrage unless you are running your own polygon node, because a lot of transaction fails.

**Comment by proro485** [comment]
Also if you want to learn more <a href="https://www.youtube.com/channel/UCSZsGiuLtMMgHEOm2I4-7GA/videos">Check this channel out</a>. I learnt a lot of stuff from him and his repo.

**Comment by rinconcsc** [comment]
Thank you bro

**Comment by rinconcsc** [comment]
But finally, where (in the directory) and how do I have to create the .env file

**Comment by proro485** [comment]
![image](https://user-images.githubusercontent.com/72189840/163216819-e1a4096a-d021-40c9-ba53-6dc856798fca.png)

**Comment by proro485** [comment]
I think that would have answered your question.

**Comment by proro485** [comment]
bro delete that image, people would empty your account. and yeah that is correct.

**Comment by rinconcsc** [comment]
Hi again, I have another issue...
 
<img width="405" alt="image" src="https://user-images.githubusercontent.com/92592623/163238751-b1094569-2239-4c8c-a074-ca1b9ae27dc6.png">

Can you help?

**Comment by rinconcsc** [comment]
I put in the PRIVATE_KEY, my alchemy API KEY with the 0x before

**Comment by proro485** [comment]
Bro order doesn't matter make sure variable name is correct and don't put any " ". Also lookup how to know private key for the wallet on the YouTube or google.
