### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by rolandweb3** [proro485/zrx-arbitrage-bot#8]
var error = new Error(message); Why am I getting this message in the terminal?

**Comment by proro485** [comment]
I'm not maintaining this repo anymore.

**Comment by rolandweb3** [comment]
Could you please update it, I really need it and I will really appreciate it 🙏

**Comment by saedmohamad** [comment]
please

**Comment by rolandweb3** [comment]
> please

Hello, any problem
